---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: task-2
  name: task-2
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: task-2
  type: LoadBalancer


---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: task-2
  name: task-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-2
  strategy: {}
  template:
    metadata:
      labels:
        app: task-2
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 8080
          name: http

