---
# Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: task-4
  name: task-4
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8000
  selector:
    app: task-4
  type: LoadBalancer


---
# Deployment 1
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: task-4
    version: "1"
  name: task-4-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-4
      version: "1"
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: task-4
        version: "1"
    spec:
      containers:
      - image: marcmer/demo-app:v1
        name: demo-app
        ports:
        - containerPort: 8000
          name: http
---
# Deployment 2
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: task-4
    version: "2"
  name: task-4-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-4
      version: "2"
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: task-4
        version: "2"
    spec:
      containers:
      - image: marcmer/demo-app:v2
        name: demo-app
        ports:
        - containerPort: 8000
          name: http
