apiVersion: v1
kind: Pod
metadata:
  name: task-3
spec:
  containers:
  - image: ubuntu
    name: ubuntu
    command:
    - "/bin/bash"
    - "-c"
    args:
    - tail -f /dev/null
# crashed because ubuntu exited