apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-3
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: azurefile
  resources:
    requests:
      storage: 100M