apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: task-2
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: task-2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
       - type: Pods
         value: 4
         periodSeconds: 5

      selectPolicy: Max
# behavior:
  # scaleDown:
    # policies:
      # - type: Pods
        # value: 4
        # periodSeconds: 60
      # - type: Percent
        # value: 10
        # periodSeconds: 60
