apiVersion: v1
kind: Pod
metadata:
  name: task-4
spec:
  containers:
  - image: ubuntu
    name: ubuntu
    command:
    - "/bin/bash"
    - "-c"
    args:
    - id
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      runAsNonRoot: true