apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-4
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: managed
  resources:
    requests:
      storage: 100M